services:
    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        volumes:
            - ${KAVITA_MANGA}:/manga
            - ${KAVITA_CONFIG}:/kavita/config
        ports:
            - "5090:5000"
        restart: unless-stopped