version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest
        volumes:
            - /media/redacerubuntu/files1/downloads/manga/asurascans:/manga
            - /media/redacerubuntu/qfiles/developer/docker/kavita/config:/kavita/config
        ports:
            - "5090:5000"
        restart: unless-stopped