version: "2.1"
services:
  sonarr:
    user: root
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr_config:/config
      - sonarr_tv:/tv #optional
      - sonarr_downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
volumes:
  sonarr_config:
  sonarr_tv:
  sonarr_downloads:
  