version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/redacerubuntu/files/docker/sonarr/config:/config
      - /media/redacerubuntu/files/docker/sonarr/tv:/tv #optional
      - /media/redacerubuntu/files/docker/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped