version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=5040
    volumes:
      - /media/redacerubuntu/qfiles/developer/docker/qbittorrent/config:/config
      - /media/redacerubuntu/qfiles/developer/docker/qbittorrent/downloads:/downloads
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/yts:/jellyfin/movies
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/tv:/jellyfin/tvshows
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/cartoons:/jellyfin/cartoons
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/zombies:/jellyfin/zombies
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/kids:/jellyfin/kids
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/series:/jellyfin/series
    ports:
      - 5040:5040
      - 5041:6881
      - 5042:6881/udp
    restart: unless-stopped