services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama/data:/root/.ollama

  # chromadb:
  #   image: chromadb/chroma:latest
  #   container_name: chroma
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./data/chromadb/chroma:/chroma/chroma
  qdrant-vector-db:
    image: qdrant/qdrant:latest # Official Qdrant Docker Image
    container_name: qdrant
    ports:
      - "6333:6333" # API Endpoint for Vector Queries (QDRANT_API_KEY optional)
    environment:
      - PARENT_DIR=/qdrant/storage
    volumes:
      - ./data/qdrant/storage:/qdrant/storage