services:
  ollama:
    image: ollama/ollama:${OLLAMA_VERSION}
    container_name: ollama-app
    ports:
      - ${OLLAMA_PORT_11434}:11434
    volumes:
      - ./data/ollama/data:/root/.ollama

  # chromadb:
  #   image: chromadb/chroma:latest
  #   container_name: chroma
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./data/chromadb/chroma:/chroma/chroma
  qdrant-vector-db:
    image: qdrant/qdrant:${QDRANT_VERSION} # Official Qdrant Docker Image
    container_name: qdrant-vector-db
    ports:
      - ${QDRANT_PORT_6333}:6333 # API Endpoint for Vector Queries (QDRANT_API_KEY optional)
    environment:
      - PARENT_DIR=/qdrant/storage
    volumes:
      - ./data/qdrant/storage:/qdrant/storage