docker exec -it ollama-app ollama pull nomic-embed-text
docker exec -it ollama-app ollama pull qwen3.5:4b
docker exec -it ollama-app ollama pull qwen2.5-coder:0.5b
docker exec -it ollama-app ollama pull qwen2.5-coder:1.5b
docker exec -it ollama-app ollama pull qwen2.5-coder:3b
docker exec -it ollama-app ollama pull qwen2.5-coder:7b
docker exec -it ollama-app ollama pull ALIENTELLIGENCE/doctorai
docker exec -it ollama-app ollama pull medgemma:4b
docker exec -it ollama-app ollama pull medgemma:27b
docker exec -it ollama-app ollama pull thewindmom/llama3-med42-8b:latest
docker exec -it ollama-app ollama pull qwen2.5-coder:14b
docker exec -it ollama-app ollama pull opencoder:8b
