services:
  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "${CONTAINER_NODE_PORT_80}:${NODE_PORT_80}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres-dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  postgres-dev:
    container_name: postgres-dev
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_5432}:5432"
volumes:
  postgres-dev-data: