version: '3'

services:
  nginx:
    image: nginx
    ports:
        - "80:80" 
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/etc/nginx/html
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create shared-net