services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq-web
    restart: always
    ports:
      - ${RABBITMQ_PORT_5672}:5672
      - ${RABBITMQ_PORT_15672}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - ${RABBITMQ_DATA_LIB}:/var/lib/rabbitmq/
      - ${RABBITMQ_DATA_LOG}:/var/log/rabbitmq
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."