# Use postgres/test101 as user/password credentials
#run "docker network create shared-net" to create network before running this compose file
services:
  postgres:
    image: postgres:18.2
    container_name: postgresql_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test101
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-datavolume:/var/lib/postgresql/data
    restart: always
    networks:
    - shared-net
networks:
  shared-net:
    external: true
volumes:
  postgresql-datavolume: