version: '3.1'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test101
      ME_CONFIG_MONGODB_URL: mongodb://root:test101@mongo:27017/
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create shared-net