version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create shared-net