services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ${PORTAINER_DATA}:/data
    ports:
      - ${PORTAINER_PORT_8000}:8000
      - ${PORTAINER_PORT_9443}:9443
      - ${PORTAINER_PORT_9000}:9000
    restart: unless-stopped
