version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /media/redacerubuntu/files/docker/calibre/config:/config
      - /media/redacerubuntu/files/docker/calibre/books:/books
    ports:
      - 5000:8083
    restart: unless-stopped
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create shared-net