services:
  jenkins:
    container_name: jenkins-web
    image: jenkins/jenkins:${JENKINS_VERSION}
    restart: always
    volumes:
        - ${JENKINS_HOME}:/var/jenkins_home
    ports:
        - ${JENKINS_PORT_8080}:8080 
        - ${JENKINS_PORT_50000}:50000