# Use root/test101 as user/password credentials
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test101
    volumes:
      - mongo-configvolume:/data/configdb
      - mongo-dbvolume:/data/db
    ports:
        - 27017:27017
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create shared-net
volumes:
  mongo-configvolume:
  mongo-dbvolume:
  
