services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - mariadb-volume:/bitnami/mariadb
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create magento-network
volumes:
  mariadb-volume:

# $ docker volume create --name mariadb_data
# docker run -d --name mariadb \
#   --env ALLOW_EMPTY_PASSWORD=yes \
#   --env MARIADB_USER=bn_magento \
#   --env MARIADB_PASSWORD=bitnami \
#   --env MARIADB_DATABASE=bitnami_magento \
#   --network magento-network \
#   --volume mariadb_data:/bitnami/mariadb \
#   bitnami/mariadb:latest