version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      # - /media/redacerubuntu/files/docker/jellyfin/config:/config
      # - /media/redacerubuntu/files/docker/jellyfin/tvshows:/data/tvshows
      # - /media/sf_tv:/data/tvshows
      # - /media/redacerubuntu/files/docker/jellyfin/movies:/data/movies
      # - /media/sf_yts:/data/movies
      - /media/redacerubuntu/qfiles/developer/docker/jellyfin/config:/config
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/yts:/data/movies
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/tv:/data/tvshows
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/nyaa:/data/nyaa
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/cartoons:/data/cartoons
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/zombies:/data/zombies
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/kids:/data/kids
      - /media/redacerubuntu/qfiles/downloads/qbittorrent/default/series:/data/series
      # - /media/redacerubuntu/files1/downloads/manga/asurascans:/data/asurascans
      # - /media/redacerubuntu/files1/docker/calibre/books:/data/books
    ports:
      - 5080:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
    - shared-net
networks:
  shared-net:
    external: true
#docker network create shared-net