services:
  karaokeforever:
    image: david510c/karaoke-forever:latest
    container_name: karaokeforever
    volumes:
      - ${KARAOKEFOREVER_CDGFILES}:/cdgfiles
    ports:
      - ${KARAOKEFOREVER_PORT80}:80
    restart: unless-stopped
    # networks:
    # - shared-net
# networks:
#   shared-net:
#     external: true
#docker network create shared-net