services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${MYLAR3_CONFIG}:/config
      - ${KAVITA_COMICS}:/comics
      - ${KAVITA_DOWNLODS}:/downloads
    ports:
      - 5100:8090
    restart: unless-stopped